### ISSUE TITLE
Ghost 2 vs. 3?

### ISSUE THREAD

**Issue by daxm** [selfhostedshow/ghost-example#1]
The docker-compose appears to reference ghost:2-alpine.  Why not ghost:3?

**Comment by ironicbadger** [comment]
I hadn't actually noticed that v3 was out. What's the difference?

**Comment by daxm** [comment]
To be honest, I have no idea.  :-)  I was hoping you could explain to me why ghost:2.

**Comment by ironicbadger** [comment]
https://ghost.org/3/

`ghost:2` because that's what I ran for the last year+. I'm upgrading to 3 as we speak and will update the code as appropriate.

**Comment by ironicbadger** [comment]
Modified the `docker-compose.yaml` file for v3. The upgrade from v2 to v3 was seamless here.
